[package]
name = "ecgfp5-playgroud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecgfp5 = { git = "https://github.com/lopeetall/ecgfp5"}
rand = "0.8.5"